 <h2> Missing Values</h2>

<p> The usual notation for missing values is NaN. </p>

<p> Functions we can use include<p\>
    <ul>
     <li> dropna() select the data that we would like to drop
     <li> fillna() fill missing values with a desired values like a mean or the most frequent value
     <li> isnull() check the entries of the data in the dataframe where we have missing values
    <\ul>

<h3> Droping data </h3>

In [1]:
from numpy import nan as NA 
import pandas as pd
import numpy as np 

In [2]:
data = pd.Series([1, NA, 3.5, NA, 7])  

In [3]:
data[data.isnull()] #returns values and indices of the Series where we have missing values 

1   NaN
3   NaN
dtype: float64

In [4]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
     [NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [5]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [6]:
data.dropna(how  = "all") #drops the rows constituting only of missing data 

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [7]:
data[4] = NA

In [8]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [9]:
data.dropna(how = "all", axis = 1)
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [10]:
df = pd.DataFrame(np.random.randn(7, 3))
df

0         1         2
0  0.250427  0.968171 -0.800585
1  1.640781  0.237553 -1.137693
2 -0.209553  1.311548 -0.845768
3  0.006508 -0.404485 -0.363868
4 -1.110697 -0.063283 -0.574743
5 -0.558983  0.877430  1.665406
6  0.835932  0.210161  0.599582

In [11]:
df.iloc[:4,1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0  0.250427       NaN       NaN
1  1.640781       NaN       NaN
2 -0.209553       NaN -0.845768
3  0.006508       NaN -0.363868
4 -1.110697 -0.063283 -0.574743
5 -0.558983  0.877430  1.665406
6  0.835932  0.210161  0.599582

In [12]:
df.dropna(thresh = 2) #select rows with a certain number of observations i.e. columns with two non missing values

0         1         2
2 -0.209553       NaN -0.845768
3  0.006508       NaN -0.363868
4 -1.110697 -0.063283 -0.574743
5 -0.558983  0.877430  1.665406
6  0.835932  0.210161  0.599582

<h3> Filling data </h3>

In [13]:
df.fillna(0)

0         1         2
0  0.250427  0.000000  0.000000
1  1.640781  0.000000  0.000000
2 -0.209553  0.000000 -0.845768
3  0.006508  0.000000 -0.363868
4 -1.110697 -0.063283 -0.574743
5 -0.558983  0.877430  1.665406
6  0.835932  0.210161  0.599582

In [14]:
df.fillna({1:0.5, 2:0.7}) #note that fillna returns a new object by default

0         1         2
0 -1.182814  0.500000  0.700000
1  0.306944  0.500000  0.700000
2 -0.804611  0.500000 -0.105274
3 -1.104482  0.500000  0.110162
4  0.760391  0.158885 -1.123857
5  0.408986 -2.651022 -1.673769
6 -0.971582  1.903234  1.835813

In [15]:
df.fillna(0, inplace = True)
df

0         1         2
0 -1.182814  0.000000  0.000000
1  0.306944  0.000000  0.000000
2 -0.804611  0.000000 -0.105274
3 -1.104482  0.000000  0.110162
4  0.760391  0.158885 -1.123857
5  0.408986 -2.651022 -1.673769
6 -0.971582  1.903234  1.835813

In [16]:
df = pd.DataFrame(np.random.randn(6, 3))

In [17]:
df.iloc[4:, 1] =NA
df.iloc[2:,2] = NA
df

0         1         2
0  0.279128 -1.776805 -1.158480
1 -1.026777 -0.327648  0.199822
2 -1.248659  0.109939       NaN
3 -0.033051 -0.464863       NaN
4  0.917852       NaN       NaN
5  0.322020       NaN       NaN

In [18]:
df.fillna(method = "ffill")
df

0         1         2
0  0.279128 -1.776805 -1.158480
1 -1.026777 -0.327648  0.199822
2 -1.248659  0.109939       NaN
3 -0.033051 -0.464863       NaN
4  0.917852       NaN       NaN
5  0.322020       NaN       NaN

In [19]:
df.fillna(method = "ffill", limit = 2)

0         1         2
0  0.279128 -1.776805 -1.158480
1 -1.026777 -0.327648  0.199822
2 -1.248659  0.109939  0.199822
3 -0.033051 -0.464863  0.199822
4  0.917852 -0.464863       NaN
5  0.322020 -0.464863       NaN

In [20]:
data = pd.Series([1,NA,4,NA, 3.5])
data

0    1.0
1    NaN
2    4.0
3    NaN
4    3.5
dtype: float64

In [21]:
data.fillna(data.mean()) #replace the missing values with the mean value, another candidate is the median

0    1.000000
1    2.833333
2    4.000000
3    2.833333
4    3.500000
dtype: float64

<h3> Ways to fill missing values </h3>
            

 <p>
    <ul>
        <li> fill missing values with a desired number, usually the mean or median 
        <li> method back filling bfill or forward filling ffill 
        <li> limit, use that in interpolation with the ffill or bfill method
        <li> remember that the fillna method (as well as the dropna) returns a new object. Inplace = True operates on the initial dataframe
    <ul\>
 <p\>

<h3> Duplicated Values

In [22]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
       'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [23]:
data.duplicated()  #checks if a row is duplicate value of another row

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [24]:
data.drop_duplicates() # simply drop the duplicated rows

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [25]:
data['v1'] = range(7)

In [26]:
data.drop_duplicates(['k1']) #select the column on which you  will drop the duplicates
data                         #again notice that the drop_duplicates() creates a new object

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [27]:
# drop_duplicates() returns the first observed values and cuts down the subsequent duplicates
# we can select to cut down the first occurence of the sequence and return the last values

In [28]:
data.drop_duplicates(['k1', 'k2'], keep = 'last') # this will cut down the index 5 but will return the index 6 


k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

<h3> Transforming Data with a function or a mapping <\h3>

In [29]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
      'Pastrami', 'corned beef', 'Bacon',
      'pastrami', 'honey ham', 'nova lox'],
      'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [30]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
} #consider that we would like to change via mapping the food to the its raw material 

In [31]:
lower_string = data['food'].str.lower() #make the strings from mixed lowercased/uppercased to lowercased, 
                                        #notice that str.lower() is a Series method

In [32]:
lower_string

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [33]:
data['animal']  = lower_string.map(meat_to_animal) # a Series can accept through mapping a dict for changing its elements to the values of the dict, elements and keys should be 1-1.

In [34]:
data['animal'] = data['food'].map(lambda x: meat_to_animal[x.lower()])
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

<p> Therefore, we see that map() can transform a subset of data to a format of our desire, however there are
    easier and more flexible ways go do so, one of them being the replace() function.
<p\>

In [35]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [36]:
data.replace(-999, NA)
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [37]:
data.replace([-999,-1000], NA) #replace a list of elements with one value

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [38]:
data.replace([-999, -1000], [NA, 0]) #replac the elements of a list with another list by 1-1

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [39]:
data.replace({-999: 0, -1000: NA}) # replacement can also occur via dict
                                  #notice that the method replace() is different from the str.replace() 
                                  # the last one is  a string substitution element-wise

0    1.0
1    0.0
2    2.0
3    0.0
4    NaN
5    3.0
dtype: float64

In [40]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
       index=['Ohio', 'Colorado', 'New York'],
       columns=['one', 'two', 'three', 'four'])

In [41]:
transform  = lambda x: x[:4].upper()

In [42]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [43]:
data.rename(index = str.title, columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [44]:
data.rename(index={'Ohio': 'Indiana'},
            columns={'three': 'peekaboo'}, #inplace = True/False
           )

one  two  peekaboo  four
Indiana     0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

<h3> Discretization and Binning <h3\>

In [45]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
group_names = ['millenia', 'young_adult', 'middle-age', 'senior']
cats = pd.cut(ages, bins, labels = group_names, right = False, #precision = number [numerical data]
             )
cats

[millenia, millenia, young_adult, young_adult, millenia, ..., young_adult, senior, middle-age, middle-age, young_adult]
Length: 12
Categories (4, object): [millenia < young_adult < middle-age < senior]

In [46]:
cats.categories

Index(['millenia', 'young_adult', 'middle-age', 'senior'], dtype='object')

In [47]:
cats.codes

array([0, 0, 1, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [48]:
pd.value_counts(cats)

young_adult    4
millenia       4
middle-age     3
senior         1
dtype: int64

In [49]:
#instead of bins you can cut into quartiles i.e. 
#pd.cut(data, 4)
#pd.cat(data, [0.2,0.4,0.6,0.8,1.]) create your own percentiles 

In [50]:
data = pd.DataFrame(np.random.randn(1000, 4))
outliers = data[(np.abs(data) >3).any(1)]  #find the outliers in the entire dataframe 
outliers

0         1         2         3
51   0.623368  1.268148  3.031012 -0.362788
73  -0.118262  1.416828 -0.496228  3.076088
285  1.467609  3.101406 -1.417975 -0.166705
488  1.301277 -3.237083 -0.498917 -0.828074
657  1.183246 -0.513212  2.250054 -3.146739
658 -1.465842  3.068336 -1.998737 -1.836667
799  0.156952  0.047644 -1.209734 -3.196567
973  3.013680  1.105652 -1.499445 -1.275601

<h3> Permutation and Sampling </h3>

In [51]:
df = pd.DataFrame(np.arange(20).reshape((5,4)))

In [52]:
sampler = np.random.permutation(5)
sampler

array([3, 2, 0, 1, 4])

In [53]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19

In [54]:
df.sample(n=10 ,replace=True) #replace allows for repetitions

0   1   2   3
1   4   5   6   7
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
2   8   9  10  11
1   4   5   6   7
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
1   4   5   6   7

<h3> Dummy Variables </h3>

In [55]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [56]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]


In [57]:
pd.get_dummies(pd.cut(values, bins)) # this will introduce dummy variables in each cateogorization
                                     #1 means existence of the value and 0 means otherwise

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

<h3> String Manupulation</h3>

In [58]:
#split() and strip() can be used together to put strings in a list and then trim any whitespaces 

In [59]:
val = "a, b, guide" 

In [61]:
list_val = val.split(",")
list_val

['a', ' b', ' guide']

In [63]:
no_space_ListVal = [x.strip() for x in list_val] # strip will trim any white spaces 
no_space_ListVal

['a', 'b', 'guide']

In [65]:
#check  the directory of functions for string manipulation in mckinney 

<h3> <i>Regexp </i></h3>

In [66]:
#regexp can be used for pattern matching, substitution and splitting 